### ISSUE TITLE
p_code.c

### ISSUE THREAD

**Issue by arblake** [turnimator/tpforth#1]
Where is the p_code.c file that is required for compiling?

**Comment by arblake** [comment]
Fixed, changed the make file. Thus:
ARCH ?= 64
CC := clang
CFLAGS = -O3 -m$(ARCH) 
srcfiles := $(shell find . -name "*.c")
incfiles := $(shell find . -name "*.h")

tpforth: $(srcfiles) $(incfiles)
	$(CC) $(CFLAGS) $(srcfiles) -o $@ -lm

run: tpforth 
	./tpforth

clean:
	rm -f ./tpforth

**Comment by turnimator** [comment]
My use of the term P-CODE was very unfortunate, and I have refactored them into SmartTokens, smtok.c
The compilation takes place in smtok_p smtok_compile_word(char *src).
